INSERT INTO ITEM (BARCODE, NAME, UNIT, CATEGORY, SUB_CATEGORY, PRICE) VALUES ('ITEM000000', '可口可乐', '瓶', '', '', 3.00);
INSERT INTO ITEM (BARCODE, NAME, UNIT, CATEGORY, SUB_CATEGORY, PRICE) VALUES ('ITEM000001', '雪碧', '瓶', '', '', 3.00);
INSERT INTO ITEM (BARCODE, NAME, UNIT, CATEGORY, SUB_CATEGORY, PRICE) VALUES ('ITEM000004', '电池', '个', '', '', 2.00);

INSERT INTO PROMOTION (PROMOTIONNAME, BARCODES) VALUES ('SELL_BY_95', 'ITEM000000');
INSERT INTO PROMOTION (PROMOTIONNAME, BARCODES) VALUES ('BUY_TWO_GET_ONE_FREE', 'ITEM000001,ITEM000004');
